import crypto from 'crypto'
import PDFDocument from 'pdfkit'
import nodemailer from 'nodemailer'

import { serverConfigErrorMessage, supabaseAdmin } from '@/lib/admin'
import { getCompanySettings } from '@/lib/services/companySettings'
import {
  listEmailRecipients,
  recipientMatchesInspection,
} from '@/lib/services/emailDistribution'
import { getDefaultInspectionTemplate, renderTemplate } from '@/lib/services/emailTemplates'

type InspectionForArchive = {
  id: string
  machineId: string
  machineName: string
  machineArea: string | null
  templateName: string
  status: string
  startedAt: string | null
  completedAt: string | null
  operatorName: string
  dueAt: string | null
}

type InspectionItemForArchive = {
  id: string
  displayOrder: number
  question: string
  questionType: string
  answer: string | null
  comments: string | null
  photos: unknown[]
  signatureData: string | null
}

type DefectForArchive = {
  id: string
  title: string
  severity: string
  status: string
  description: string | null
}

function formatDateTime(value: string | null) {
  if (!value) return 'N/A'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return 'N/A'
  return date.toLocaleString('en-GB', { hour12: false })
}

function formatDuration(startedAt: string | null, completedAt: string | null) {
  if (!startedAt || !completedAt) return 'N/A'
  const startMs = new Date(startedAt).getTime()
  const endMs = new Date(completedAt).getTime()
  if (Number.isNaN(startMs) || Number.isNaN(endMs) || endMs < startMs) return 'N/A'

  const totalMinutes = Math.round((endMs - startMs) / 60000)
  const hours = Math.floor(totalMinutes / 60)
  const minutes = totalMinutes % 60
  if (hours <= 0) return `${minutes}m`
  return `${hours}h ${minutes}m`
}

function buildPdfBuffer(input: {
  company: Awaited<ReturnType<typeof getCompanySettings>>
  inspection: InspectionForArchive
  items: InspectionItemForArchive[]
  defects: DefectForArchive[]
  overallResult: 'PASS' | 'FAIL' | 'INCOMPLETE'
}) {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 36 })
    const chunks: Buffer[] = []

    doc.on('data', (chunk) => chunks.push(Buffer.from(chunk)))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    doc.fillColor('#0f172a').fontSize(24).text(input.company.companyName)
    doc.moveDown(0.25)
    doc.fillColor('#475569').fontSize(10)
    doc.text(input.company.address || '')
    doc.text(input.company.telephone || '')
    doc.text(input.company.email || '')
    doc.text(input.company.website || '')

    doc.moveDown(1)
    doc.fillColor('#0f172a').fontSize(16).text('Inspection Archive Report')
    doc.moveDown(0.5)

    const details: Array<[string, string]> = [
      ['Machine', input.inspection.machineName],
      ['Department', input.inspection.machineArea || 'N/A'],
      ['Template', input.inspection.templateName],
      ['Inspector', input.inspection.operatorName],
      ['Started', formatDateTime(input.inspection.startedAt)],
      ['Completed', formatDateTime(input.inspection.completedAt)],
      ['Duration', formatDuration(input.inspection.startedAt, input.inspection.completedAt)],
      ['Result', input.overallResult],
      ['Reference', input.inspection.id],
    ]

    for (const [label, value] of details) {
      doc.fontSize(10).fillColor('#334155').text(`${label}: `, { continued: true })
      doc.fillColor('#0f172a').text(value)
    }

    doc.moveDown(1)
    doc.fontSize(12).fillColor('#0f172a').text('Checklist')
    doc.moveDown(0.3)

    for (const item of input.items) {
      doc.fontSize(10).fillColor('#0f172a').text(`${item.displayOrder}. ${item.question}`)
      doc.fillColor('#475569').text(`Answer: ${item.answer || 'N/A'}`)
      if (item.comments) doc.text(`Comments: ${item.comments}`)
      if (Array.isArray(item.photos) && item.photos.length > 0) doc.text(`Photos: ${item.photos.length} attached`)
      if (item.signatureData) doc.text('Signature: Captured')
      doc.moveDown(0.3)
    }

    doc.moveDown(0.5)
    doc.fontSize(12).fillColor('#0f172a').text('Defects')
    doc.moveDown(0.3)

    if (input.defects.length === 0) {
      doc.fontSize(10).fillColor('#475569').text('No defects logged.')
    } else {
      for (const defect of input.defects) {
        doc.fontSize(10).fillColor('#0f172a').text(`${defect.title} [${defect.severity}] - ${defect.status}`)
        if (defect.description) {
          doc.fillColor('#475569').text(defect.description)
        }
        doc.moveDown(0.3)
      }
    }

    const footer = input.company.reportFooter || 'Generated by MGMT Inspect'
    doc.moveDown(1)
    doc.fontSize(9).fillColor('#64748b').text(footer)

    const range = doc.bufferedPageRange()
    for (let i = range.start; i < range.start + range.count; i += 1) {
      doc.switchToPage(i)
      doc.fontSize(8)
      doc.fillColor('#94a3b8')
      doc.text(`Page ${i + 1} of ${range.count}`, 36, doc.page.height - 28, {
        width: doc.page.width - 72,
        align: 'right',
      })
    }

    doc.end()
  })
}

async function loadInspectionArchiveData(inspectionId: string) {
  if (!supabaseAdmin) throw new Error(serverConfigErrorMessage)

  const { data: inspectionData, error: inspectionError } = await supabaseAdmin
    .from('inspections')
    .select('id, machine_id, template_name, status, started_at, completed_at, operator_name, due_at')
    .eq('id', inspectionId)
    .maybeSingle()

  if (inspectionError) throw inspectionError
  if (!inspectionData) throw new Error('Inspection not found.')

  const { data: machineData, error: machineError } = await supabaseAdmin
    .from('machines')
    .select('id, name, area')
    .eq('id', inspectionData.machine_id as string)
    .maybeSingle()

  if (machineError) throw machineError

  const { data: itemsData, error: itemsError } = await supabaseAdmin
    .from('inspection_items')
    .select('id, display_order, question, question_type, answer, comments, photos, signature_data')
    .eq('inspection_id', inspectionId)
    .order('display_order', { ascending: true })

  if (itemsError) throw itemsError

  const { data: defectsData, error: defectsError } = await supabaseAdmin
    .from('defects')
    .select('id, title, severity, status, description')
    .eq('inspection_id', inspectionId)

  if (defectsError) throw defectsError

  const items = (itemsData ?? []).map((row) => ({
    id: row.id as string,
    displayOrder: Number(row.display_order ?? 0),
    question: row.question as string,
    questionType: row.question_type as string,
    answer: (row.answer as string | null) ?? null,
    comments: (row.comments as string | null) ?? null,
    photos: Array.isArray(row.photos) ? row.photos : [],
    signatureData: (row.signature_data as string | null) ?? null,
  }))

  const defects = (defectsData ?? []).map((row) => ({
    id: row.id as string,
    title: row.title as string,
    severity: row.severity as string,
    status: row.status as string,
    description: (row.description as string | null) ?? null,
  }))

  const failCount = items.filter((item) => item.answer === 'fail').length
  const incompleteCount = items.filter((item) => !item.answer).length
  const overallResult: 'PASS' | 'FAIL' | 'INCOMPLETE' = failCount > 0
    ? 'FAIL'
    : incompleteCount > 0
      ? 'INCOMPLETE'
      : 'PASS'

  const inspection: InspectionForArchive = {
    id: inspectionData.id as string,
    machineId: inspectionData.machine_id as string,
    machineName: (machineData?.name as string) || 'Unknown Machine',
    machineArea: (machineData?.area as string | null) ?? null,
    templateName: (inspectionData.template_name as string) || 'Inspection',
    status: (inspectionData.status as string) || 'Completed',
    startedAt: (inspectionData.started_at as string | null) ?? null,
    completedAt: (inspectionData.completed_at as string | null) ?? null,
    operatorName: (inspectionData.operator_name as string) || 'Unknown User',
    dueAt: (inspectionData.due_at as string | null) ?? null,
  }

  return { inspection, items, defects, overallResult }
}

function resolveSmtpTransport() {
  const host = process.env.SMTP_HOST
  const port = Number(process.env.SMTP_PORT || '587')
  const user = process.env.SMTP_USER
  const pass = process.env.SMTP_PASS
  const from = process.env.SMTP_FROM

  if (!host || !user || !pass || !from) {
    return null
  }

  const transporter = nodemailer.createTransport({
    host,
    port,
    secure: port === 465,
    auth: { user, pass },
  })

  return { transporter, from }
}

async function logDelivery(input: {
  inspectionId: string
  archiveId: string | null
  pdfGenerated: boolean
  emailSent: boolean
  archived: boolean
  status: 'success' | 'failed' | 'retrying' | 'skipped'
  failureReason?: string | null
  retryCount: number
  recipients: Array<{ type: 'to' | 'cc' | 'bcc'; email: string; name: string }>
}) {
  if (!supabaseAdmin) throw new Error(serverConfigErrorMessage)

  await supabaseAdmin.from('archive_delivery_logs').insert([
    {
      inspection_id: input.inspectionId,
      archive_id: input.archiveId,
      pdf_generated: input.pdfGenerated,
      email_sent: input.emailSent,
      archived: input.archived,
      status: input.status,
      failure_reason: input.failureReason ?? null,
      retry_count: input.retryCount,
      recipient_snapshot: input.recipients,
    },
  ])
}

async function updateInspectionArchiveState(input: {
  inspectionId: string
  archiveStatus: 'pending' | 'archived' | 'failed'
  archiveRetryCount?: number
  archiveLastError?: string | null
  archiveReference?: string | null
  archivedAt?: string | null
}) {
  if (!supabaseAdmin) throw new Error(serverConfigErrorMessage)

  const updates: Record<string, unknown> = {
    archive_status: input.archiveStatus,
    archive_last_attempt_at: new Date().toISOString(),
  }

  if (input.archiveRetryCount !== undefined) updates.archive_retry_count = input.archiveRetryCount
  if (input.archiveLastError !== undefined) updates.archive_last_error = input.archiveLastError
  if (input.archiveReference !== undefined) updates.archived_reference = input.archiveReference
  if (input.archivedAt !== undefined) updates.archived_at = input.archivedAt

  await supabaseAdmin.from('inspections').update(updates).eq('id', input.inspectionId)
}

export async function archiveInspectionAndSendEmail(params: {
  inspectionId: string
  triggeredBy?: string
}) {
  if (!supabaseAdmin) throw new Error(serverConfigErrorMessage)

  const { inspection, items, defects, overallResult } = await loadInspectionArchiveData(params.inspectionId)

  const company = await getCompanySettings()
  const pdf = await buildPdfBuffer({
    company,
    inspection,
    items,
    defects,
    overallResult,
  })

  const checksum = crypto.createHash('sha256').update(pdf).digest('hex')
  const fileName = `inspection-${inspection.id}.pdf`

  const { data: archiveData, error: archiveError } = await supabaseAdmin
    .from('inspection_archives')
    .upsert(
      [
        {
          inspection_id: inspection.id,
          file_name: fileName,
          content_type: 'application/pdf',
          pdf_base64: pdf.toString('base64'),
          checksum,
          generated_at: new Date().toISOString(),
          generated_by: params.triggeredBy ?? null,
        },
      ],
      { onConflict: 'inspection_id' }
    )
    .select('id')
    .single()

  if (archiveError || !archiveData) {
    await updateInspectionArchiveState({
      inspectionId: inspection.id,
      archiveStatus: 'failed',
      archiveLastError: archiveError?.message || 'Failed to save PDF archive.',
    })

    await logDelivery({
      inspectionId: inspection.id,
      archiveId: null,
      pdfGenerated: false,
      emailSent: false,
      archived: false,
      status: 'failed',
      failureReason: archiveError?.message || 'Failed to save PDF archive.',
      retryCount: 0,
      recipients: [],
    })

    throw archiveError ?? new Error('Failed to save PDF archive.')
  }

  const archiveId = archiveData.id as string

  const recipients = (await listEmailRecipients())
    .filter((recipient) => recipient.enabled)
    .filter((recipient) => {
      if (!recipientMatchesInspection({
        deliveryScope: recipient.deliveryScope,
        hasDefects: defects.length > 0,
        overallResult,
      })) {
        return false
      }

      if (recipient.departmentFilter && recipient.departmentFilter !== inspection.machineArea) {
        return false
      }

      if (recipient.machineFilter && recipient.machineFilter !== inspection.machineId) {
        return false
      }

      return true
    })

  const grouped = {
    to: recipients.filter((r) => r.recipientType === 'to'),
    cc: recipients.filter((r) => r.recipientType === 'cc'),
    bcc: recipients.filter((r) => r.recipientType === 'bcc'),
  }

  const template = await getDefaultInspectionTemplate()

  const subject = renderTemplate({
    raw: template.subject,
    vars: {
      Machine: inspection.machineName,
      Inspector: inspection.operatorName,
      Department: inspection.machineArea || 'N/A',
      Result: overallResult,
      Date: formatDateTime(inspection.completedAt),
      Reference: inspection.id,
      Company: company.companyName,
    },
  })

  const body = renderTemplate({
    raw: template.body,
    vars: {
      Machine: inspection.machineName,
      Inspector: inspection.operatorName,
      Department: inspection.machineArea || 'N/A',
      Result: overallResult,
      Date: formatDateTime(inspection.completedAt),
      Reference: inspection.id,
      Company: company.companyName,
    },
  })

  const signature = renderTemplate({
    raw: template.signature,
    vars: {
      Machine: inspection.machineName,
      Inspector: inspection.operatorName,
      Department: inspection.machineArea || 'N/A',
      Result: overallResult,
      Date: formatDateTime(inspection.completedAt),
      Reference: inspection.id,
      Company: company.companyName,
    },
  })

  const smtp = resolveSmtpTransport()

  if (!smtp) {
    // SMTP not configured - queue for later delivery instead of failing
    await updateInspectionArchiveState({
      inspectionId: inspection.id,
      archiveStatus: 'pending',
      archiveLastError: null,
      archiveReference: archiveId,
    })

    await logDelivery({
      inspectionId: inspection.id,
      archiveId,
      pdfGenerated: true,
      emailSent: false,
      archived: false,
      status: 'skipped',
      failureReason: 'SMTP configuration is not available. Email will be queued for delivery.',
      retryCount: 0,
      recipients: recipients.map((r) => ({
        type: r.recipientType,
        email: r.email,
        name: r.name,
      })),
    })

    // Queue all emails for later delivery
    if (supabaseAdmin) {
      for (const recipient of recipients) {
        await supabaseAdmin.from('email_queue').insert([
          {
            inspection_id: inspection.id,
            recipient_email: recipient.email,
            recipient_type: recipient.recipientType,
            subject,
            body: `${body}\n\n${signature}`,
            status: 'pending',
            attempt_count: 0,
            created_at: new Date().toISOString(),
          },
        ])
      }
    }

    return {
      inspectionId: inspection.id,
      archiveId,
      recipients: recipients.length,
      overallResult,
      queuedForDelivery: true,
    }
  }

  if (grouped.to.length === 0 && grouped.cc.length === 0 && grouped.bcc.length === 0) {
    await updateInspectionArchiveState({
      inspectionId: inspection.id,
      archiveStatus: 'failed',
      archiveLastError: 'No recipients are configured for this inspection.',
    })

    await logDelivery({
      inspectionId: inspection.id,
      archiveId,
      pdfGenerated: true,
      emailSent: false,
      archived: false,
      status: 'failed',
      failureReason: 'No recipients are configured for this inspection.',
      retryCount: 0,
      recipients: [],
    })

    throw new Error('No recipients are configured for this inspection.')
  }

  await smtp.transporter.sendMail({
    from: smtp.from,
    to: grouped.to.map((r) => r.email).join(', ') || undefined,
    cc: grouped.cc.map((r) => r.email).join(', ') || undefined,
    bcc: grouped.bcc.map((r) => r.email).join(', ') || undefined,
    subject,
    text: `${body}\n\n${signature}`,
    attachments: [
      {
        filename: fileName,
        content: pdf,
        contentType: 'application/pdf',
      },
    ],
  })

  await logDelivery({
    inspectionId: inspection.id,
    archiveId,
    pdfGenerated: true,
    emailSent: true,
    archived: true,
    status: 'success',
    retryCount: 0,
    recipients: recipients.map((r) => ({
      type: r.recipientType,
      email: r.email,
      name: r.name,
    })),
  })

  await updateInspectionArchiveState({
    inspectionId: inspection.id,
    archiveStatus: 'archived',
    archiveRetryCount: 0,
    archiveLastError: null,
    archiveReference: archiveId,
    archivedAt: new Date().toISOString(),
  })

  return {
    inspectionId: inspection.id,
    archiveId,
    recipients: recipients.length,
    overallResult,
  }
}

export async function retryFailedArchiveDeliveries(maxRetries: number) {
  if (!supabaseAdmin) throw new Error(serverConfigErrorMessage)

  const { data, error } = await supabaseAdmin
    .from('inspections')
    .select('id, archive_retry_count')
    .eq('archive_status', 'failed')
    .lt('archive_retry_count', maxRetries)
    .order('completed_at', { ascending: true })

  if (error) throw error

  let retried = 0
  let success = 0

  for (const row of data ?? []) {
    const inspectionId = row.id as string
    const currentRetryCount = Number(row.archive_retry_count ?? 0)

    await supabaseAdmin
      .from('inspections')
      .update({ archive_retry_count: currentRetryCount + 1 })
      .eq('id', inspectionId)

    retried += 1
    try {
      await archiveInspectionAndSendEmail({ inspectionId })
      success += 1
    } catch {
      await logDelivery({
        inspectionId,
        archiveId: null,
        pdfGenerated: false,
        emailSent: false,
        archived: false,
        status: 'retrying',
        failureReason: 'Retry failed.',
        retryCount: currentRetryCount + 1,
        recipients: [],
      })
    }
  }

  return { retried, success }
}
