function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

export function textToHtmlParagraphs(text: string) {
  const escaped = escapeHtml(text)
  return escaped
    .split(/\n\n+/)
    .map((paragraph) => `<p>${paragraph.replace(/\n/g, '<br/>')}</p>`)
    .join('')
}

export function buildInspectionArchiveEmailTemplate(input: {
  machineName: string
  templateName: string
  inspector: string
  result: 'PASS' | 'FAIL' | 'INCOMPLETE'
  completedAt: string
  reference: string
}) {
  const resolvedResult = input.result === 'PASS' ? 'PASS' : 'FAIL'
  const subject = `Inspection Complete - ${input.machineName} - ${resolvedResult}`

  const text = [
    'Hello,',
    '',
    resolvedResult === 'PASS' ? 'Inspection completed successfully.' : 'Inspection completed with failures.',
    '',
    `Machine: ${input.machineName}`,
    `Template: ${input.templateName}`,
    `Inspector: ${input.inspector}`,
    `Result: ${resolvedResult}`,
    `Completed: ${input.completedAt}`,
    `Reference Number: ${input.reference}`,
    '',
    'The archived inspection report is attached.',
    '',
    'Regards,',
    '',
    'MGMT Inspect',
  ].join('\n')

  const html = [
    '<div style="font-family:Arial,sans-serif;background:#f8fafc;padding:18px;color:#0f172a;">',
    '<div style="max-width:680px;margin:0 auto;background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">',
    '<div style="padding:16px 20px;background:#0f172a;color:#ffffff;">',
    '<h2 style="margin:0;font-size:20px;">Inspection Complete</h2>',
    `<p style="margin:8px 0 0;"><span style="display:inline-block;padding:4px 10px;border-radius:999px;background:${resolvedResult === 'PASS' ? '#16a34a' : '#dc2626'};color:#fff;font-size:12px;">${resolvedResult}</span></p>`,
    '</div>',
    '<div style="padding:18px 20px;font-size:14px;line-height:1.6;">',
    `<p>${resolvedResult === 'PASS' ? 'Inspection completed successfully.' : 'Inspection completed with failures.'}</p>`,
    '<p>',
    `Machine: ${escapeHtml(input.machineName)}<br/>`,
    `Template: ${escapeHtml(input.templateName)}<br/>`,
    `Inspector: ${escapeHtml(input.inspector)}<br/>`,
    `Completed: ${escapeHtml(input.completedAt)}<br/>`,
    `Reference Number: ${escapeHtml(input.reference)}`,
    '</p>',
    '<p>The PDF inspection report is attached.</p>',
    '<p style="margin-bottom:0;color:#475569;">MGMT Inspect</p>',
    '</div></div></div>',
  ].join('')

  return { subject, text, html }
}

export function buildSmtpTestEmailTemplate(input: { companyName: string; generatedAt: string }) {
  const subject = 'MGMT Inspect SMTP Test'
  const text = [
    'Hello,',
    '',
    'SMTP configuration is active and this test email was sent successfully.',
    'A sample PDF generated by the shared PDF service is attached.',
    '',
    `Company: ${input.companyName}`,
    `Generated: ${input.generatedAt}`,
    '',
    'Regards,',
    '',
    'MGMT Inspect',
  ].join('\n')

  const html = [
    '<p>Hello,</p>',
    '<p>SMTP configuration is active and this test email was sent successfully.<br/>',
    'A sample PDF generated by the shared PDF service is attached.</p>',
    `<p>Company: ${escapeHtml(input.companyName)}<br/>Generated: ${escapeHtml(input.generatedAt)}</p>`,
    '<p>Regards,<br/><br/>MGMT Inspect</p>',
  ].join('')

  return { subject, text, html }
}

export function buildArchiveRetryStatusTemplate(input: {
  success: boolean
  machineName: string
  reference: string
  completedAt: string
  errorMessage?: string
}) {
  const subject = input.success ? 'Archive Delivery Retry - Success' : 'Archive Delivery Retry - Failed'
  const header = input.success
    ? 'Archive delivery retry completed successfully.'
    : 'Archive delivery retry failed.'

  const text = [
    'Hello,',
    '',
    header,
    '',
    `Machine: ${input.machineName}`,
    `Reference Number: ${input.reference}`,
    `Timestamp: ${input.completedAt}`,
    ...(input.errorMessage ? [`Error: ${input.errorMessage}`] : []),
    '',
    'Regards,',
    '',
    'MGMT Inspect',
  ].join('\n')

  return {
    subject,
    text,
    html: [
      '<div style="font-family:Arial,sans-serif;background:#f8fafc;padding:18px;color:#0f172a;">',
      '<div style="max-width:680px;margin:0 auto;background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">',
      '<div style="padding:16px 20px;background:#0f172a;color:#ffffff;">',
      `<h2 style="margin:0;font-size:20px;">${escapeHtml(subject)}</h2>`,
      '</div>',
      `<div style="padding:18px 20px;font-size:14px;line-height:1.6;">${textToHtmlParagraphs(text)}</div>`,
      '</div></div>',
    ].join(''),
  }
}

export function buildReminderEmailTemplate(input: {
  machine: string
  department: string
  inspectionTemplate: string
  dueDate: string
  dueTime: string
  assignedUser: string
  inspectionLink: string
  stageLabel: string
}) {
  const subject = `Inspection Reminder - ${input.machine} - ${input.stageLabel}`
  const text = [
    'Hello,',
    '',
    `A scheduled inspection reminder is due (${input.stageLabel}).`,
    '',
    `Machine: ${input.machine}`,
    `Department: ${input.department}`,
    `Inspection Template: ${input.inspectionTemplate}`,
    `Due Date: ${input.dueDate}`,
    `Due Time: ${input.dueTime}`,
    `Assigned User: ${input.assignedUser}`,
    `Inspection Link: ${input.inspectionLink}`,
    '',
    'Regards,',
    '',
    'MGMT Inspect',
  ].join('\n')

  const html = `
    <div style="font-family:Arial,sans-serif;background:#f8fafc;padding:18px;color:#0f172a;">
      <div style="max-width:680px;margin:0 auto;background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">
        <div style="background:#0f172a;color:#fff;padding:16px 20px;">
          <h2 style="margin:0;font-size:20px;">Inspection Reminder</h2>
          <p style="margin:6px 0 0;font-size:13px;opacity:0.9;">${input.stageLabel}</p>
        </div>
        <div style="padding:18px 20px;line-height:1.6;font-size:14px;">
          <p style="margin-top:0;">A scheduled inspection reminder is due.</p>
          <p style="margin:0;">
            Machine: ${escapeHtml(input.machine)}<br/>
            Department: ${escapeHtml(input.department)}<br/>
            Inspection Template: ${escapeHtml(input.inspectionTemplate)}<br/>
            Due Date: ${escapeHtml(input.dueDate)}<br/>
            Due Time: ${escapeHtml(input.dueTime)}<br/>
            Assigned User: ${escapeHtml(input.assignedUser)}
          </p>
          <p><a href="${escapeHtml(input.inspectionLink)}" style="display:inline-block;background:#0f766e;color:#fff;padding:10px 14px;border-radius:8px;text-decoration:none;">Open Inspection</a></p>
          <p style="margin-bottom:0;color:#475569;">MGMT Inspect</p>
        </div>
      </div>
    </div>
  `

  return { subject, text, html }
}