import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const showDevelopmentBanner =
  process.env.VERCEL_GIT_COMMIT_REF === "development";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        className={`min-h-full flex flex-col ${
          showDevelopmentBanner ? "pt-10" : ""
        }`}
      >
        {showDevelopmentBanner ? (
          <div className="fixed inset-x-0 top-0 z-[9999] flex h-10 items-center justify-center bg-orange-500 px-4 text-center text-sm font-semibold tracking-wide text-white sm:text-base">
            🛠 DEVELOPMENT BUILD
          </div>
        ) : null}
        {children}
      </body>
    </html>
  );
}
