-- Release 1: Operations & Retention

-- Extend schedule frequencies with Fortnightly.
do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname = 'machine_inspection_templates_frequency_check'
      and conrelid = 'public.machine_inspection_templates'::regclass
  ) then
    alter table public.machine_inspection_templates
      drop constraint machine_inspection_templates_frequency_check;
  end if;

  alter table public.machine_inspection_templates
    add constraint machine_inspection_templates_frequency_check
    check (inspection_frequency in (
      'Daily', 'Weekly', 'Fortnightly', 'Monthly', 'Quarterly', 'Six Monthly', 'Annually', 'Custom'
    ));
end
$$;

do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname = 'inspection_schedules_frequency_check'
      and conrelid = 'public.inspection_schedules'::regclass
  ) then
    alter table public.inspection_schedules
      drop constraint inspection_schedules_frequency_check;
  end if;

  alter table public.inspection_schedules
    add constraint inspection_schedules_frequency_check
    check (frequency in (
      'Daily', 'Weekly', 'Fortnightly', 'Monthly', 'Quarterly', 'Six Monthly', 'Annually', 'Custom'
    ));
end
$$;

-- Company settings used by reports and outbound email templates.
create table if not exists public.company_settings (
  id uuid primary key default uuid_generate_v4(),
  company_name text not null default 'MGMT Inspect',
  logo_url text,
  address text,
  telephone text,
  email text,
  website text,
  report_footer text,
  report_primary_color text not null default '#0f766e',
  report_accent_color text not null default '#0f172a',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint company_settings_singleton check (true)
);

create unique index if not exists idx_company_settings_singleton
  on public.company_settings ((true));

insert into public.company_settings (
  company_name,
  report_footer,
  report_primary_color,
  report_accent_color
)
select
  'MGMT Inspect',
  'Generated by MGMT Inspect',
  '#0f766e',
  '#0f172a'
where not exists (select 1 from public.company_settings);

-- Email distribution recipients.
create table if not exists public.email_distribution_recipients (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  email text not null,
  recipient_type text not null,
  enabled boolean not null default true,
  delivery_scope text not null default 'all_inspections',
  department_filter text,
  machine_filter uuid references public.machines(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint email_distribution_recipients_type_check check (recipient_type in ('to', 'cc', 'bcc')),
  constraint email_distribution_recipients_scope_check check (
    delivery_scope in ('all_inspections', 'passed_inspections', 'failed_inspections', 'failed_only', 'defects_only')
  )
);

create index if not exists idx_email_distribution_recipients_enabled
  on public.email_distribution_recipients(enabled, recipient_type);

create index if not exists idx_email_distribution_recipients_delivery_scope
  on public.email_distribution_recipients(delivery_scope);

create index if not exists idx_email_distribution_recipients_department
  on public.email_distribution_recipients(department_filter);

create index if not exists idx_email_distribution_recipients_machine
  on public.email_distribution_recipients(machine_filter);

-- Administrator email templates.
create table if not exists public.email_templates (
  id uuid primary key default uuid_generate_v4(),
  name text not null unique,
  subject text not null,
  body text not null,
  signature text not null,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

insert into public.email_templates (name, subject, body, signature, active)
select
  'inspection_archive_default',
  'Inspection {{Reference}} - {{Machine}} ({{Result}})',
  'Hello,\n\nInspection {{Reference}} for {{Machine}} ({{Department}}) was completed by {{Inspector}} on {{Date}} with result {{Result}}.\n\nPlease find the archived PDF report attached.',
  'Regards,\n{{Company}}',
  true
where not exists (
  select 1 from public.email_templates where name = 'inspection_archive_default'
);

-- Archive metadata and immutable PDF payload reference.
create table if not exists public.inspection_archives (
  id uuid primary key default uuid_generate_v4(),
  inspection_id uuid not null unique references public.inspections(id) on delete cascade,
  file_name text not null,
  content_type text not null default 'application/pdf',
  pdf_base64 text not null,
  checksum text,
  generated_at timestamp with time zone not null default now(),
  generated_by uuid references auth.users(id) on delete set null,
  created_at timestamp with time zone not null default now()
);

create index if not exists idx_inspection_archives_generated_at
  on public.inspection_archives(generated_at);

-- Delivery attempt log for archive workflow.
create table if not exists public.archive_delivery_logs (
  id uuid primary key default uuid_generate_v4(),
  inspection_id uuid not null references public.inspections(id) on delete cascade,
  archive_id uuid references public.inspection_archives(id) on delete set null,
  pdf_generated boolean not null default false,
  email_sent boolean not null default false,
  archived boolean not null default false,
  recipient_snapshot jsonb not null default '[]'::jsonb,
  status text not null,
  failure_reason text,
  retry_count integer not null default 0,
  created_at timestamp with time zone not null default now(),
  constraint archive_delivery_logs_status_check check (status in ('success', 'failed', 'retrying', 'skipped'))
);

create index if not exists idx_archive_delivery_logs_inspection_id
  on public.archive_delivery_logs(inspection_id, created_at desc);

create index if not exists idx_archive_delivery_logs_status
  on public.archive_delivery_logs(status, retry_count, created_at);

-- Retention configuration.
create table if not exists public.retention_settings (
  id uuid primary key default uuid_generate_v4(),
  retention_days integer not null default 90,
  use_custom boolean not null default false,
  custom_days integer,
  max_delivery_retries integer not null default 3,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint retention_settings_days_check check (retention_days in (30, 60, 90, 180) or use_custom),
  constraint retention_settings_custom_days_check check (custom_days is null or custom_days >= 1),
  constraint retention_settings_retries_check check (max_delivery_retries >= 0)
);

create unique index if not exists idx_retention_settings_singleton
  on public.retention_settings ((true));

insert into public.retention_settings (retention_days, use_custom, custom_days, max_delivery_retries)
select 90, false, null, 3
where not exists (select 1 from public.retention_settings);

create table if not exists public.scheduled_cleanup_runs (
  id uuid primary key default uuid_generate_v4(),
  started_at timestamp with time zone not null default now(),
  completed_at timestamp with time zone,
  status text not null default 'running',
  summary jsonb not null default '{}'::jsonb,
  constraint scheduled_cleanup_runs_status_check check (status in ('running', 'success', 'failed'))
);

create index if not exists idx_scheduled_cleanup_runs_started_at
  on public.scheduled_cleanup_runs(started_at desc);

-- Add archive workflow state directly on inspections for retention guards.
alter table public.inspections
  add column if not exists archive_status text not null default 'pending',
  add column if not exists archived_at timestamp with time zone,
  add column if not exists archived_reference text,
  add column if not exists archive_retry_count integer not null default 0,
  add column if not exists archive_last_error text,
  add column if not exists archive_last_attempt_at timestamp with time zone;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'inspections_archive_status_check'
      and conrelid = 'public.inspections'::regclass
  ) then
    alter table public.inspections
      add constraint inspections_archive_status_check
      check (archive_status in ('pending', 'archived', 'failed'));
  end if;
end
$$;

create index if not exists idx_inspections_archive_status
  on public.inspections(archive_status, archive_retry_count, completed_at);

create index if not exists idx_inspections_archived_at
  on public.inspections(archived_at);

-- Keep updated_at columns current.
do $$
begin
  if exists (
    select 1 from pg_proc
    where proname = 'update_updated_at_column'
      and pronamespace = 'public'::regnamespace
  ) then
    if not exists (
      select 1 from pg_trigger
      where tgname = 'update_company_settings_updated_at'
        and tgrelid = 'public.company_settings'::regclass
    ) then
      create trigger update_company_settings_updated_at
        before update on public.company_settings
        for each row execute function public.update_updated_at_column();
    end if;

    if not exists (
      select 1 from pg_trigger
      where tgname = 'update_email_distribution_recipients_updated_at'
        and tgrelid = 'public.email_distribution_recipients'::regclass
    ) then
      create trigger update_email_distribution_recipients_updated_at
        before update on public.email_distribution_recipients
        for each row execute function public.update_updated_at_column();
    end if;

    if not exists (
      select 1 from pg_trigger
      where tgname = 'update_email_templates_updated_at'
        and tgrelid = 'public.email_templates'::regclass
    ) then
      create trigger update_email_templates_updated_at
        before update on public.email_templates
        for each row execute function public.update_updated_at_column();
    end if;

    if not exists (
      select 1 from pg_trigger
      where tgname = 'update_retention_settings_updated_at'
        and tgrelid = 'public.retention_settings'::regclass
    ) then
      create trigger update_retention_settings_updated_at
        before update on public.retention_settings
        for each row execute function public.update_updated_at_column();
    end if;
  end if;
end
$$;

-- RLS
alter table public.company_settings enable row level security;
alter table public.email_distribution_recipients enable row level security;
alter table public.email_templates enable row level security;
alter table public.inspection_archives enable row level security;
alter table public.archive_delivery_logs enable row level security;
alter table public.retention_settings enable row level security;
alter table public.scheduled_cleanup_runs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'company_settings'
      and policyname = 'Service role can manage company settings'
  ) then
    create policy "Service role can manage company settings"
      on public.company_settings
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'company_settings'
      and policyname = 'Authenticated users can read company settings'
  ) then
    create policy "Authenticated users can read company settings"
      on public.company_settings
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'email_distribution_recipients'
      and policyname = 'Service role can manage distribution recipients'
  ) then
    create policy "Service role can manage distribution recipients"
      on public.email_distribution_recipients
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'email_distribution_recipients'
      and policyname = 'Authenticated users can read distribution recipients'
  ) then
    create policy "Authenticated users can read distribution recipients"
      on public.email_distribution_recipients
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'email_templates'
      and policyname = 'Service role can manage email templates'
  ) then
    create policy "Service role can manage email templates"
      on public.email_templates
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'email_templates'
      and policyname = 'Authenticated users can read email templates'
  ) then
    create policy "Authenticated users can read email templates"
      on public.email_templates
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'inspection_archives'
      and policyname = 'Service role can manage inspection archives'
  ) then
    create policy "Service role can manage inspection archives"
      on public.inspection_archives
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'inspection_archives'
      and policyname = 'Authenticated users can read inspection archives'
  ) then
    create policy "Authenticated users can read inspection archives"
      on public.inspection_archives
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'archive_delivery_logs'
      and policyname = 'Service role can manage archive delivery logs'
  ) then
    create policy "Service role can manage archive delivery logs"
      on public.archive_delivery_logs
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'archive_delivery_logs'
      and policyname = 'Authenticated users can read archive delivery logs'
  ) then
    create policy "Authenticated users can read archive delivery logs"
      on public.archive_delivery_logs
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'retention_settings'
      and policyname = 'Service role can manage retention settings'
  ) then
    create policy "Service role can manage retention settings"
      on public.retention_settings
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'retention_settings'
      and policyname = 'Authenticated users can read retention settings'
  ) then
    create policy "Authenticated users can read retention settings"
      on public.retention_settings
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'scheduled_cleanup_runs'
      and policyname = 'Service role can manage cleanup runs'
  ) then
    create policy "Service role can manage cleanup runs"
      on public.scheduled_cleanup_runs
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'scheduled_cleanup_runs'
      and policyname = 'Authenticated users can read cleanup runs'
  ) then
    create policy "Authenticated users can read cleanup runs"
      on public.scheduled_cleanup_runs
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;
end
$$;
