-- Release 1 complete schema audit upgrade (idempotent)
-- This migration is safe to run on existing installations.

create extension if not exists "uuid-ossp";

-- ---------------------------------------------------------------------------
-- Ensure Release 1 operations tables exist (compatibility-safe)
-- ---------------------------------------------------------------------------

create table if not exists public.company_settings (
  id uuid primary key default uuid_generate_v4(),
  company_name text not null default 'MGMT Inspect',
  logo_url text,
  address text,
  telephone text,
  email text,
  website text,
  report_footer text,
  report_primary_color text not null default '#0f766e',
  report_accent_color text not null default '#0f172a',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.company_settings
  add column if not exists company_name text not null default 'MGMT Inspect',
  add column if not exists logo_url text,
  add column if not exists address text,
  add column if not exists telephone text,
  add column if not exists email text,
  add column if not exists website text,
  add column if not exists report_footer text,
  add column if not exists report_primary_color text not null default '#0f766e',
  add column if not exists report_accent_color text not null default '#0f172a',
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now();

create unique index if not exists idx_company_settings_singleton
  on public.company_settings ((true));

insert into public.company_settings (
  company_name,
  report_footer,
  report_primary_color,
  report_accent_color
)
select
  'MGMT Inspect',
  'Generated by MGMT Inspect',
  '#0f766e',
  '#0f172a'
where not exists (select 1 from public.company_settings);

create table if not exists public.email_distribution_recipients (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  email text not null,
  recipient_type text not null,
  enabled boolean not null default true,
  delivery_scope text not null default 'all_inspections',
  department_filter text,
  machine_filter uuid references public.machines(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.email_distribution_recipients
  add column if not exists name text,
  add column if not exists email text,
  add column if not exists recipient_type text,
  add column if not exists enabled boolean not null default true,
  add column if not exists delivery_scope text not null default 'all_inspections',
  add column if not exists department_filter text,
  add column if not exists machine_filter uuid,
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now();

update public.email_distribution_recipients
set
  name = coalesce(name, 'Recipient'),
  email = coalesce(email, 'unknown@example.com'),
  recipient_type = coalesce(recipient_type, 'to')
where name is null or email is null or recipient_type is null;

alter table public.email_distribution_recipients
  alter column name set not null,
  alter column email set not null,
  alter column recipient_type set not null;

create table if not exists public.email_templates (
  id uuid primary key default uuid_generate_v4(),
  name text not null unique,
  subject text not null,
  body text not null,
  signature text not null,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.email_templates
  add column if not exists name text,
  add column if not exists subject text,
  add column if not exists body text,
  add column if not exists signature text,
  add column if not exists active boolean not null default true,
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now();

update public.email_templates
set
  name = coalesce(name, 'inspection_archive_default'),
  subject = coalesce(subject, 'Inspection {{Reference}} - {{Machine}} ({{Result}})'),
  body = coalesce(body, 'Inspection {{Reference}} completed for {{Machine}} with result {{Result}}.'),
  signature = coalesce(signature, 'Regards, {{Company}}')
where name is null or subject is null or body is null or signature is null;

alter table public.email_templates
  alter column name set not null,
  alter column subject set not null,
  alter column body set not null,
  alter column signature set not null;

insert into public.email_templates (name, subject, body, signature, active)
select
  'inspection_archive_default',
  'Inspection {{Reference}} - {{Machine}} ({{Result}})',
  'Hello,\n\nInspection {{Reference}} for {{Machine}} ({{Department}}) was completed by {{Inspector}} on {{Date}} with result {{Result}}.\n\nPlease find the archived PDF report attached.',
  'Regards,\n{{Company}}',
  true
where not exists (
  select 1 from public.email_templates where name = 'inspection_archive_default'
);

create table if not exists public.inspection_archives (
  id uuid primary key default uuid_generate_v4(),
  inspection_id uuid not null unique references public.inspections(id) on delete cascade,
  file_name text not null,
  content_type text not null default 'application/pdf',
  pdf_base64 text not null,
  checksum text,
  archive_reference text,
  generated_at timestamp with time zone not null default now(),
  generated_by uuid references auth.users(id) on delete set null,
  created_at timestamp with time zone not null default now()
);

alter table public.inspection_archives
  add column if not exists file_name text,
  add column if not exists content_type text not null default 'application/pdf',
  add column if not exists pdf_base64 text,
  add column if not exists checksum text,
  add column if not exists archive_reference text,
  add column if not exists generated_at timestamp with time zone not null default now(),
  add column if not exists generated_by uuid,
  add column if not exists created_at timestamp with time zone not null default now();

create table if not exists public.archive_delivery_logs (
  id uuid primary key default uuid_generate_v4(),
  inspection_id uuid not null references public.inspections(id) on delete cascade,
  archive_id uuid references public.inspection_archives(id) on delete set null,
  pdf_generated boolean not null default false,
  email_sent boolean not null default false,
  archived boolean not null default false,
  recipient_snapshot jsonb not null default '[]'::jsonb,
  status text not null,
  archive_status text,
  archive_last_error text,
  archive_timestamp timestamp with time zone,
  archive_reference text,
  failure_reason text,
  retry_count integer not null default 0,
  created_at timestamp with time zone not null default now()
);

alter table public.archive_delivery_logs
  add column if not exists archive_id uuid,
  add column if not exists pdf_generated boolean not null default false,
  add column if not exists email_sent boolean not null default false,
  add column if not exists archived boolean not null default false,
  add column if not exists recipient_snapshot jsonb not null default '[]'::jsonb,
  add column if not exists status text,
  add column if not exists archive_status text,
  add column if not exists archive_last_error text,
  add column if not exists archive_timestamp timestamp with time zone,
  add column if not exists archive_reference text,
  add column if not exists failure_reason text,
  add column if not exists retry_count integer not null default 0,
  add column if not exists created_at timestamp with time zone not null default now();

update public.archive_delivery_logs
set
  status = coalesce(status, 'skipped'),
  archive_status = coalesce(archive_status, status, 'skipped'),
  archive_last_error = coalesce(archive_last_error, failure_reason),
  archive_timestamp = coalesce(archive_timestamp, created_at)
where status is null
   or archive_status is null
   or (archive_last_error is null and failure_reason is not null)
   or archive_timestamp is null;

alter table public.archive_delivery_logs
  alter column status set not null;

create table if not exists public.retention_settings (
  id uuid primary key default uuid_generate_v4(),
  retention_days integer not null default 90,
  use_custom boolean not null default false,
  custom_days integer,
  max_delivery_retries integer not null default 3,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.retention_settings
  add column if not exists retention_days integer not null default 90,
  add column if not exists use_custom boolean not null default false,
  add column if not exists custom_days integer,
  add column if not exists max_delivery_retries integer not null default 3,
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now();

create unique index if not exists idx_retention_settings_singleton
  on public.retention_settings ((true));

insert into public.retention_settings (retention_days, use_custom, custom_days, max_delivery_retries)
select 90, false, null, 3
where not exists (select 1 from public.retention_settings);

create table if not exists public.scheduled_cleanup_runs (
  id uuid primary key default uuid_generate_v4(),
  started_at timestamp with time zone not null default now(),
  completed_at timestamp with time zone,
  status text not null default 'running',
  summary jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.scheduled_cleanup_runs
  add column if not exists started_at timestamp with time zone not null default now(),
  add column if not exists completed_at timestamp with time zone,
  add column if not exists status text not null default 'running',
  add column if not exists summary jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamp with time zone not null default now(),
  add column if not exists updated_at timestamp with time zone not null default now();

-- ---------------------------------------------------------------------------
-- Compatibility objects explicitly requested by Release 1 audit
-- ---------------------------------------------------------------------------

create table if not exists public.email_recipients (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  email text not null,
  recipient_type text not null,
  enabled boolean not null default true,
  delivery_scope text not null default 'all_inspections',
  department_filter text,
  machine_filter uuid references public.machines(id) on delete set null,
  source_recipient_id uuid references public.email_distribution_recipients(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.inspection_email_history (
  id uuid primary key default uuid_generate_v4(),
  inspection_id uuid not null references public.inspections(id) on delete cascade,
  template_id uuid references public.email_templates(id) on delete set null,
  archive_id uuid references public.inspection_archives(id) on delete set null,
  recipient_email text not null,
  recipient_type text not null default 'to',
  subject text,
  status text not null default 'queued',
  error_message text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.archive_jobs (
  id uuid primary key default uuid_generate_v4(),
  inspection_id uuid references public.inspections(id) on delete set null,
  archive_id uuid references public.inspection_archives(id) on delete set null,
  archive_delivery_log_id uuid references public.archive_delivery_logs(id) on delete set null,
  status text not null default 'pending',
  archive_status text not null default 'pending',
  archive_last_error text,
  archive_timestamp timestamp with time zone,
  archive_reference text,
  retry_count integer not null default 0,
  next_retry_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- ---------------------------------------------------------------------------
-- Add missing archive compatibility columns on inspections
-- ---------------------------------------------------------------------------

alter table public.inspections
  add column if not exists archive_status text not null default 'pending',
  add column if not exists archive_retry_count integer not null default 0,
  add column if not exists archive_last_error text,
  add column if not exists archive_last_attempt_at timestamp with time zone,
  add column if not exists archived_at timestamp with time zone,
  add column if not exists archived_reference text,
  add column if not exists archive_timestamp timestamp with time zone,
  add column if not exists archive_reference text;

update public.inspections
set
  archive_timestamp = coalesce(archive_timestamp, archived_at),
  archived_at = coalesce(archived_at, archive_timestamp),
  archive_reference = coalesce(archive_reference, archived_reference),
  archived_reference = coalesce(archived_reference, archive_reference),
  archive_status = coalesce(archive_status, 'pending')
where archive_timestamp is null
   or archived_at is null
   or archive_reference is null
   or archived_reference is null
   or archive_status is null;

-- Keep alias columns synchronized.
create or replace function public.sync_inspection_archive_compat_columns()
returns trigger as $$
begin
  new.archived_at := coalesce(new.archived_at, new.archive_timestamp);
  new.archive_timestamp := coalesce(new.archive_timestamp, new.archived_at);
  new.archived_reference := coalesce(new.archived_reference, new.archive_reference);
  new.archive_reference := coalesce(new.archive_reference, new.archived_reference);
  return new;
end;
$$ language plpgsql;

do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgname = 'sync_inspection_archive_compat_columns'
      and tgrelid = 'public.inspections'::regclass
  ) then
    create trigger sync_inspection_archive_compat_columns
      before insert or update on public.inspections
      for each row
      execute function public.sync_inspection_archive_compat_columns();
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- Constraints
-- ---------------------------------------------------------------------------

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'email_distribution_recipients_type_check'
      and conrelid = 'public.email_distribution_recipients'::regclass
  ) then
    alter table public.email_distribution_recipients
      add constraint email_distribution_recipients_type_check
      check (recipient_type in ('to', 'cc', 'bcc'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'email_distribution_recipients_scope_check'
      and conrelid = 'public.email_distribution_recipients'::regclass
  ) then
    alter table public.email_distribution_recipients
      add constraint email_distribution_recipients_scope_check
      check (delivery_scope in ('all_inspections', 'passed_inspections', 'failed_inspections', 'failed_only', 'defects_only'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'archive_delivery_logs_status_check'
      and conrelid = 'public.archive_delivery_logs'::regclass
  ) then
    alter table public.archive_delivery_logs
      add constraint archive_delivery_logs_status_check
      check (status in ('success', 'failed', 'retrying', 'skipped'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'retention_settings_days_check'
      and conrelid = 'public.retention_settings'::regclass
  ) then
    alter table public.retention_settings
      add constraint retention_settings_days_check
      check (retention_days in (30, 60, 90, 180) or use_custom);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'retention_settings_custom_days_check'
      and conrelid = 'public.retention_settings'::regclass
  ) then
    alter table public.retention_settings
      add constraint retention_settings_custom_days_check
      check (custom_days is null or custom_days >= 1);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'retention_settings_retries_check'
      and conrelid = 'public.retention_settings'::regclass
  ) then
    alter table public.retention_settings
      add constraint retention_settings_retries_check
      check (max_delivery_retries >= 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'scheduled_cleanup_runs_status_check'
      and conrelid = 'public.scheduled_cleanup_runs'::regclass
  ) then
    alter table public.scheduled_cleanup_runs
      add constraint scheduled_cleanup_runs_status_check
      check (status in ('running', 'success', 'failed'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'inspections_archive_status_check'
      and conrelid = 'public.inspections'::regclass
  ) then
    alter table public.inspections
      add constraint inspections_archive_status_check
      check (archive_status in ('pending', 'archived', 'failed'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'inspection_email_history_status_check'
      and conrelid = 'public.inspection_email_history'::regclass
  ) then
    alter table public.inspection_email_history
      add constraint inspection_email_history_status_check
      check (status in ('queued', 'sent', 'failed', 'skipped'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'inspection_email_history_recipient_type_check'
      and conrelid = 'public.inspection_email_history'::regclass
  ) then
    alter table public.inspection_email_history
      add constraint inspection_email_history_recipient_type_check
      check (recipient_type in ('to', 'cc', 'bcc'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'archive_jobs_status_check'
      and conrelid = 'public.archive_jobs'::regclass
  ) then
    alter table public.archive_jobs
      add constraint archive_jobs_status_check
      check (status in ('pending', 'running', 'completed', 'failed', 'retrying', 'cancelled'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'archive_jobs_archive_status_check'
      and conrelid = 'public.archive_jobs'::regclass
  ) then
    alter table public.archive_jobs
      add constraint archive_jobs_archive_status_check
      check (archive_status in ('pending', 'archived', 'failed'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'email_recipients_type_check'
      and conrelid = 'public.email_recipients'::regclass
  ) then
    alter table public.email_recipients
      add constraint email_recipients_type_check
      check (recipient_type in ('to', 'cc', 'bcc'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'email_recipients_scope_check'
      and conrelid = 'public.email_recipients'::regclass
  ) then
    alter table public.email_recipients
      add constraint email_recipients_scope_check
      check (delivery_scope in ('all_inspections', 'passed_inspections', 'failed_inspections', 'failed_only', 'defects_only'));
  end if;
end
$$;

-- Ensure nullable FK columns actually have their FK constraints if pre-existing tables missed them.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'email_distribution_recipients_machine_filter_fkey'
      and conrelid = 'public.email_distribution_recipients'::regclass
  ) then
    alter table public.email_distribution_recipients
      add constraint email_distribution_recipients_machine_filter_fkey
      foreign key (machine_filter) references public.machines(id) on delete set null;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'archive_delivery_logs_archive_id_fkey'
      and conrelid = 'public.archive_delivery_logs'::regclass
  ) then
    alter table public.archive_delivery_logs
      add constraint archive_delivery_logs_archive_id_fkey
      foreign key (archive_id) references public.inspection_archives(id) on delete set null;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'inspection_archives_generated_by_fkey'
      and conrelid = 'public.inspection_archives'::regclass
  ) then
    alter table public.inspection_archives
      add constraint inspection_archives_generated_by_fkey
      foreign key (generated_by) references auth.users(id) on delete set null;
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

create index if not exists idx_email_distribution_recipients_enabled
  on public.email_distribution_recipients(enabled, recipient_type);
create index if not exists idx_email_distribution_recipients_delivery_scope
  on public.email_distribution_recipients(delivery_scope);
create index if not exists idx_email_distribution_recipients_department
  on public.email_distribution_recipients(department_filter);
create index if not exists idx_email_distribution_recipients_machine
  on public.email_distribution_recipients(machine_filter);

create index if not exists idx_inspection_archives_generated_at
  on public.inspection_archives(generated_at);
create unique index if not exists idx_inspection_archives_archive_reference
  on public.inspection_archives(archive_reference)
  where archive_reference is not null;

create index if not exists idx_archive_delivery_logs_inspection_id
  on public.archive_delivery_logs(inspection_id, created_at desc);
create index if not exists idx_archive_delivery_logs_status
  on public.archive_delivery_logs(status, retry_count, created_at);
create index if not exists idx_archive_delivery_logs_archive_timestamp
  on public.archive_delivery_logs(archive_timestamp);
create index if not exists idx_archive_delivery_logs_archive_reference
  on public.archive_delivery_logs(archive_reference);

create index if not exists idx_scheduled_cleanup_runs_started_at
  on public.scheduled_cleanup_runs(started_at desc);

create index if not exists idx_inspections_archive_status
  on public.inspections(archive_status, archive_retry_count, completed_at);
create index if not exists idx_inspections_archived_at
  on public.inspections(archived_at);
create index if not exists idx_inspections_archive_timestamp
  on public.inspections(archive_timestamp);
create index if not exists idx_inspections_archive_reference
  on public.inspections(archive_reference);

create index if not exists idx_email_recipients_enabled
  on public.email_recipients(enabled, recipient_type);
create index if not exists idx_email_recipients_delivery_scope
  on public.email_recipients(delivery_scope);
create index if not exists idx_email_recipients_machine_filter
  on public.email_recipients(machine_filter);
create index if not exists idx_email_recipients_source_recipient
  on public.email_recipients(source_recipient_id);

create index if not exists idx_inspection_email_history_inspection
  on public.inspection_email_history(inspection_id, created_at desc);
create index if not exists idx_inspection_email_history_status
  on public.inspection_email_history(status, sent_at);
create index if not exists idx_inspection_email_history_recipient
  on public.inspection_email_history(recipient_email);

create index if not exists idx_archive_jobs_status
  on public.archive_jobs(status, archive_status, retry_count);
create index if not exists idx_archive_jobs_inspection
  on public.archive_jobs(inspection_id, created_at desc);
create index if not exists idx_archive_jobs_next_retry_at
  on public.archive_jobs(next_retry_at);
create index if not exists idx_archive_jobs_archive_timestamp
  on public.archive_jobs(archive_timestamp);
create index if not exists idx_archive_jobs_archive_reference
  on public.archive_jobs(archive_reference);

-- ---------------------------------------------------------------------------
-- Trigger function and triggers
-- ---------------------------------------------------------------------------

create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgname = 'update_company_settings_updated_at'
      and tgrelid = 'public.company_settings'::regclass
  ) then
    create trigger update_company_settings_updated_at
      before update on public.company_settings
      for each row execute function public.update_updated_at_column();
  end if;

  if not exists (
    select 1 from pg_trigger
    where tgname = 'update_email_distribution_recipients_updated_at'
      and tgrelid = 'public.email_distribution_recipients'::regclass
  ) then
    create trigger update_email_distribution_recipients_updated_at
      before update on public.email_distribution_recipients
      for each row execute function public.update_updated_at_column();
  end if;

  if not exists (
    select 1 from pg_trigger
    where tgname = 'update_email_templates_updated_at'
      and tgrelid = 'public.email_templates'::regclass
  ) then
    create trigger update_email_templates_updated_at
      before update on public.email_templates
      for each row execute function public.update_updated_at_column();
  end if;

  if not exists (
    select 1 from pg_trigger
    where tgname = 'update_retention_settings_updated_at'
      and tgrelid = 'public.retention_settings'::regclass
  ) then
    create trigger update_retention_settings_updated_at
      before update on public.retention_settings
      for each row execute function public.update_updated_at_column();
  end if;

  if not exists (
    select 1 from pg_trigger
    where tgname = 'update_scheduled_cleanup_runs_updated_at'
      and tgrelid = 'public.scheduled_cleanup_runs'::regclass
  ) then
    create trigger update_scheduled_cleanup_runs_updated_at
      before update on public.scheduled_cleanup_runs
      for each row execute function public.update_updated_at_column();
  end if;

  if not exists (
    select 1 from pg_trigger
    where tgname = 'update_email_recipients_updated_at'
      and tgrelid = 'public.email_recipients'::regclass
  ) then
    create trigger update_email_recipients_updated_at
      before update on public.email_recipients
      for each row execute function public.update_updated_at_column();
  end if;

  if not exists (
    select 1 from pg_trigger
    where tgname = 'update_inspection_email_history_updated_at'
      and tgrelid = 'public.inspection_email_history'::regclass
  ) then
    create trigger update_inspection_email_history_updated_at
      before update on public.inspection_email_history
      for each row execute function public.update_updated_at_column();
  end if;

  if not exists (
    select 1 from pg_trigger
    where tgname = 'update_archive_jobs_updated_at'
      and tgrelid = 'public.archive_jobs'::regclass
  ) then
    create trigger update_archive_jobs_updated_at
      before update on public.archive_jobs
      for each row execute function public.update_updated_at_column();
  end if;
end
$$;

-- Seed compatibility table from canonical recipients table.
insert into public.email_recipients (
  name,
  email,
  recipient_type,
  enabled,
  delivery_scope,
  department_filter,
  machine_filter,
  source_recipient_id
)
select
  r.name,
  r.email,
  r.recipient_type,
  r.enabled,
  r.delivery_scope,
  r.department_filter,
  r.machine_filter,
  r.id
from public.email_distribution_recipients r
where not exists (
  select 1
  from public.email_recipients er
  where er.source_recipient_id = r.id
);

-- ---------------------------------------------------------------------------
-- Row level security and policies
-- ---------------------------------------------------------------------------

alter table public.company_settings enable row level security;
alter table public.email_distribution_recipients enable row level security;
alter table public.email_templates enable row level security;
alter table public.inspection_archives enable row level security;
alter table public.archive_delivery_logs enable row level security;
alter table public.retention_settings enable row level security;
alter table public.scheduled_cleanup_runs enable row level security;
alter table public.email_recipients enable row level security;
alter table public.inspection_email_history enable row level security;
alter table public.archive_jobs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'company_settings'
      and policyname = 'Service role can manage company settings'
  ) then
    create policy "Service role can manage company settings"
      on public.company_settings
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'company_settings'
      and policyname = 'Authenticated users can read company settings'
  ) then
    create policy "Authenticated users can read company settings"
      on public.company_settings
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'email_distribution_recipients'
      and policyname = 'Service role can manage distribution recipients'
  ) then
    create policy "Service role can manage distribution recipients"
      on public.email_distribution_recipients
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'email_distribution_recipients'
      and policyname = 'Authenticated users can read distribution recipients'
  ) then
    create policy "Authenticated users can read distribution recipients"
      on public.email_distribution_recipients
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'email_templates'
      and policyname = 'Service role can manage email templates'
  ) then
    create policy "Service role can manage email templates"
      on public.email_templates
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'email_templates'
      and policyname = 'Authenticated users can read email templates'
  ) then
    create policy "Authenticated users can read email templates"
      on public.email_templates
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'inspection_archives'
      and policyname = 'Service role can manage inspection archives'
  ) then
    create policy "Service role can manage inspection archives"
      on public.inspection_archives
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'inspection_archives'
      and policyname = 'Authenticated users can read inspection archives'
  ) then
    create policy "Authenticated users can read inspection archives"
      on public.inspection_archives
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'archive_delivery_logs'
      and policyname = 'Service role can manage archive delivery logs'
  ) then
    create policy "Service role can manage archive delivery logs"
      on public.archive_delivery_logs
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'archive_delivery_logs'
      and policyname = 'Authenticated users can read archive delivery logs'
  ) then
    create policy "Authenticated users can read archive delivery logs"
      on public.archive_delivery_logs
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'retention_settings'
      and policyname = 'Service role can manage retention settings'
  ) then
    create policy "Service role can manage retention settings"
      on public.retention_settings
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'retention_settings'
      and policyname = 'Authenticated users can read retention settings'
  ) then
    create policy "Authenticated users can read retention settings"
      on public.retention_settings
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'scheduled_cleanup_runs'
      and policyname = 'Service role can manage cleanup runs'
  ) then
    create policy "Service role can manage cleanup runs"
      on public.scheduled_cleanup_runs
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'scheduled_cleanup_runs'
      and policyname = 'Authenticated users can read cleanup runs'
  ) then
    create policy "Authenticated users can read cleanup runs"
      on public.scheduled_cleanup_runs
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'email_recipients'
      and policyname = 'Service role can manage email recipients'
  ) then
    create policy "Service role can manage email recipients"
      on public.email_recipients
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'email_recipients'
      and policyname = 'Authenticated users can read email recipients'
  ) then
    create policy "Authenticated users can read email recipients"
      on public.email_recipients
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'inspection_email_history'
      and policyname = 'Service role can manage inspection email history'
  ) then
    create policy "Service role can manage inspection email history"
      on public.inspection_email_history
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'inspection_email_history'
      and policyname = 'Authenticated users can read inspection email history'
  ) then
    create policy "Authenticated users can read inspection email history"
      on public.inspection_email_history
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'archive_jobs'
      and policyname = 'Service role can manage archive jobs'
  ) then
    create policy "Service role can manage archive jobs"
      on public.archive_jobs
      as permissive
      for all
      to service_role
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'archive_jobs'
      and policyname = 'Authenticated users can read archive jobs'
  ) then
    create policy "Authenticated users can read archive jobs"
      on public.archive_jobs
      as permissive
      for select
      using (auth.role() = 'authenticated');
  end if;
end
$$;
